/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route';
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index';
import { Route as errorNotFoundRouteImport } from './routes/(error)/not-found';
import { Route as authLoginRouteImport } from './routes/(auth)/login';
import { Route as AuthenticatedTopProgressBarIndexRouteImport } from './routes/_authenticated/top-progress-bar/index';
import { Route as AuthenticatedPokemonIndexRouteImport } from './routes/_authenticated/pokemon/index';
import { Route as AuthenticatedFormIndexRouteImport } from './routes/_authenticated/form/index';
import { Route as AuthenticatedPokemonIdRouteImport } from './routes/_authenticated/pokemon/$id';

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const errorNotFoundRoute = errorNotFoundRouteImport.update({
  id: '/(error)/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any);
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedTopProgressBarIndexRoute =
  AuthenticatedTopProgressBarIndexRouteImport.update({
    id: '/top-progress-bar/',
    path: '/top-progress-bar/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedPokemonIndexRoute =
  AuthenticatedPokemonIndexRouteImport.update({
    id: '/pokemon/',
    path: '/pokemon/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedFormIndexRoute = AuthenticatedFormIndexRouteImport.update({
  id: '/form/',
  path: '/form/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthenticatedPokemonIdRoute = AuthenticatedPokemonIdRouteImport.update({
  id: '/pokemon/$id',
  path: '/pokemon/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute;
  '/not-found': typeof errorNotFoundRoute;
  '/': typeof AuthenticatedIndexRoute;
  '/pokemon/$id': typeof AuthenticatedPokemonIdRoute;
  '/form': typeof AuthenticatedFormIndexRoute;
  '/pokemon': typeof AuthenticatedPokemonIndexRoute;
  '/top-progress-bar': typeof AuthenticatedTopProgressBarIndexRoute;
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute;
  '/not-found': typeof errorNotFoundRoute;
  '/': typeof AuthenticatedIndexRoute;
  '/pokemon/$id': typeof AuthenticatedPokemonIdRoute;
  '/form': typeof AuthenticatedFormIndexRoute;
  '/pokemon': typeof AuthenticatedPokemonIndexRoute;
  '/top-progress-bar': typeof AuthenticatedTopProgressBarIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren;
  '/(auth)/login': typeof authLoginRoute;
  '/(error)/not-found': typeof errorNotFoundRoute;
  '/_authenticated/': typeof AuthenticatedIndexRoute;
  '/_authenticated/pokemon/$id': typeof AuthenticatedPokemonIdRoute;
  '/_authenticated/form/': typeof AuthenticatedFormIndexRoute;
  '/_authenticated/pokemon/': typeof AuthenticatedPokemonIndexRoute;
  '/_authenticated/top-progress-bar/': typeof AuthenticatedTopProgressBarIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/login'
    | '/not-found'
    | '/'
    | '/pokemon/$id'
    | '/form'
    | '/pokemon'
    | '/top-progress-bar';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/login'
    | '/not-found'
    | '/'
    | '/pokemon/$id'
    | '/form'
    | '/pokemon'
    | '/top-progress-bar';
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/login'
    | '/(error)/not-found'
    | '/_authenticated/'
    | '/_authenticated/pokemon/$id'
    | '/_authenticated/form/'
    | '/_authenticated/pokemon/'
    | '/_authenticated/top-progress-bar/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
  authLoginRoute: typeof authLoginRoute;
  errorNotFoundRoute: typeof errorNotFoundRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/': {
      id: '/_authenticated/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/(error)/not-found': {
      id: '/(error)/not-found';
      path: '/not-found';
      fullPath: '/not-found';
      preLoaderRoute: typeof errorNotFoundRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/(auth)/login': {
      id: '/(auth)/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof authLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/top-progress-bar/': {
      id: '/_authenticated/top-progress-bar/';
      path: '/top-progress-bar';
      fullPath: '/top-progress-bar';
      preLoaderRoute: typeof AuthenticatedTopProgressBarIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/pokemon/': {
      id: '/_authenticated/pokemon/';
      path: '/pokemon';
      fullPath: '/pokemon';
      preLoaderRoute: typeof AuthenticatedPokemonIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/form/': {
      id: '/_authenticated/form/';
      path: '/form';
      fullPath: '/form';
      preLoaderRoute: typeof AuthenticatedFormIndexRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/pokemon/$id': {
      id: '/_authenticated/pokemon/$id';
      path: '/pokemon/$id';
      fullPath: '/pokemon/$id';
      preLoaderRoute: typeof AuthenticatedPokemonIdRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
  AuthenticatedPokemonIdRoute: typeof AuthenticatedPokemonIdRoute;
  AuthenticatedFormIndexRoute: typeof AuthenticatedFormIndexRoute;
  AuthenticatedPokemonIndexRoute: typeof AuthenticatedPokemonIndexRoute;
  AuthenticatedTopProgressBarIndexRoute: typeof AuthenticatedTopProgressBarIndexRoute;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPokemonIdRoute: AuthenticatedPokemonIdRoute,
  AuthenticatedFormIndexRoute: AuthenticatedFormIndexRoute,
  AuthenticatedPokemonIndexRoute: AuthenticatedPokemonIndexRoute,
  AuthenticatedTopProgressBarIndexRoute: AuthenticatedTopProgressBarIndexRoute,
};

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  errorNotFoundRoute: errorNotFoundRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
